name: Java CI/CD

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Kód letöltése
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. JDK 21 telepítése
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Maven build + tesztek, Checkstyle kihagyva
      - name: Build with Maven and skip Checkstyle
        run: mvn -B clean package -Dcheckstyle.skip=true

      # 4. In-memory mock adatbázis létrehozása (ArrayList alapú)
      - name: Mock DB Setup (ArrayList-based)
        run: |
          echo "In-memory mock DB használata: az alkalmazás tesztjei már használhatnak ArrayList alapú adattárolást"
          mkdir -p src/test/java/org/example/to_dolist/mockdb
          cat <<EOT > src/test/java/org/example/to_dolist/mockdb/MockTaskDB.java
          package org.example.to_dolist.mockdb;

          import org.example.to_dolist.domain.Task;
          import java.util.ArrayList;
          import java.util.List;
          import java.util.UUID;

          public class MockTaskDB {
              private List<Task> tasks = new ArrayList<>();

              public void addTask(Task task) {
                  tasks.add(task);
              }

              public Task getTaskById(UUID id) {
                  return tasks.stream().filter(t -> t.getId().equals(id)).findFirst().orElse(null);
              }

              public List<Task> getAllTasks() {
                  return tasks;
              }
          }
          EOT
          echo "Mock adatbázis osztály létrehozva."

      # 5. Tesztek futtatása újra, Checkstyle kihagyva
      - name: Run tests with mock DB
        run: mvn test -Dcheckstyle.skip=true

      # 6. JFrog CLI telepítése (legfrissebb stabil verzió)
      - name: Install JFrog CLI
        uses: jfrog/setup-jfrog-cli@v1
        with:
          version: '2.75.1'  # A legfrissebb stabil verzió, ami támogatja az új szintaxist

      # 7. Artifactory feltöltés (nélkülözve hitelesítést)
      - name: Upload artifact to Artifactory (no auth)
        run: |
          JAR_PATH=$(find target -name "*.jar" | head -n1)
          if [ -z "$JAR_PATH" ]; then
            echo "Nem található JAR fájl!"
            exit 1
          fi
          ARTIFACT_NAME=$(basename $JAR_PATH)
          REPO_PATH="libs-release-local/org/example/to-dolist/$(date +'%Y%m%d')/$ARTIFACT_NAME"
          
          # Feltöltés az Artifactory-ba (nélkülözve konfigurációt)
          jfrog rt u "$JAR_PATH" "$REPO_PATH" --url ${{ secrets.ARTIFACTORY_URL }}